### ISSUE TITLE
Create lpr engine file 

### ISSUE THREAD

**Issue by vinodbukya6** [NVIDIA-AI-IOT/deepstream_lpr_app#15]
Hi, I am working on License plate recognition problem. When I run deepstream app i am facing following issue.

**Starting pipeline 

0:00:00.209260524   226      0x1a87b20 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 3]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 3]: Trying to create engine from model files
WARNING: [TRT]: onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
WARNING: [TRT]: ShapedWeights.cpp:173: Weights td_dense/kernel:0 has been transposed with permutation of (1, 0)! If you plan on overwriting the weights with the Refitter API, the new weights must be pre-transposed.
WARNING: [TRT]: Tensor DataType is determined at build time for tensors not marked as input or output.
WARNING: [TRT]: Detected invalid timing cache, setup a local cache instead
python3: /dvs/p4/build/sw/rel/gpgpu/MachineLearning/myelin_trt8/src/compiler/optimizer/cublas_impl.cpp:477: void add_heuristic_results_to_tactics(std::vector<cublasLtMatmulHeuristicResult_t>&, std::vector<myelin::ir::tactic_attribute_t>&, myelin::ir::tactic_attribute_t&, bool): Assertion `false && "Invalid size written"' failed.
Aborted (core dumped)**

I am using DS 6.0. Can anyone please help me on how to solve this issue?

**Comment by imSrbh** [comment]
@vinodbukya6 @sujitbiswas 

0:00:01.256299095 30248      0x3a1bca0 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 3]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1889> [UID = 3]: deserialize engine from file :/opt/nvidia/deepstream/deepstream-6.0/sources/deepstream_python_apps/deepstream_lpr_app/models/LP/LPR/us_lprnet_baseline18_deployable.etlt_b16_gpu0_fp16.engine failed
0:00:01.256360773 30248      0x3a1bca0 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 3]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1996> [UID = 3]: deserialize backend context from engine from file :/opt/nvidia/deepstream/deepstream-6.0/sources/deepstream_python_apps/deepstream_lpr_app/models/LP/LPR/us_lprnet_baseline18_deployable.etlt_b16_gpu0_fp16.engine failed, try rebuild
0:00:01.256391192 30248      0x3a1bca0 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 3]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 3]: Trying to create engine from model files
WARNING: [TRT]: onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
WARNING: [TRT]: ShapedWeights.cpp:173: Weights td_dense/kernel:0 has been transposed with permutation of (1, 0)! If you plan on overwriting the weights with the Refitter API, the new weights must be pre-transposed.
WARNING: [TRT]: Tensor DataType is determined at build time for tensors not marked as input or output.
WARNING: [TRT]: Detected invalid timing cache, setup a local cache instead
python3: /dvs/p4/build/sw/rel/gpgpu/MachineLearning/myelin_trt8/src/compiler/optimizer/cublas_impl.cpp:477: void add_heuristic_results_to_tactics(std::vector<cublasLtMatmulHeuristicResult_t>&, std::vector<myelin::ir::tactic_attribute_t>&, myelin::ir::tactic_attribute_t&, bool): Assertion `false && "Invalid size written"' failed.
Aborted (core dumped)

The same error I am also facing.

**Comment by imSrbh** [comment]
In DS 6.0 when I am running make command, it is failing

```
root@c79ec6aed68e:/opt/nvidia/deepstream/deepstream-6.0/sources/deepstream_python_apps/deepstream_lpr_ap
p# make
make[1]: Entering directory '/opt/nvidia/deepstream/deepstream-6.0/sources/deepstream_python_apps/deepstream_lpr_app/nvinfer_custom_lpr_parser'
g++ -o libnvdsinfer_custom_impl_lpr.so nvinfer_custom_lpr_parser.cpp -Wall -Werror -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -Wl,--start-group -lnvinfer -lnvparsers -Wl,--end-group
/usr/bin/ld: cannot find -lnvinfer
/usr/bin/ld: cannot find -lnvparsers
collect2: error: ld returned 1 exit status
Makefile:37: recipe for target 'libnvdsinfer_custom_impl_lpr.so' failed
make[1]: *** [libnvdsinfer_custom_impl_lpr.so] Error 1
make[1]: Leaving directory '/opt/nvidia/deepstream/deepstream-6.0/sources/deepstream_python_apps/deepstream_lpr_app/nvinfer_custom_lpr_parser'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by vinodbukya6** [comment]
Hi, edit -L -lnvinfer -L -lnvparsers in Makefile and make. It works fine.

**Comment by imSrbh** [comment]
@vinodbukya6 
so after make,
it worked for you??
i.e. you are not getting this issue.
```
python3: /dvs/p4/build/sw/rel/gpgpu/MachineLearning/myelin_trt8/src/compiler/optimizer/cublas_impl.cpp:477: void add_heuristic_results_to_tactics(std::vector<cublasLtMatmulHeuristicResult_t>&, std::vectormyelin::ir::tactic_attribute_t&, myelin::ir::tactic_attribute_t&, bool): Assertion `false && "Invalid size written"' failed.
```

**Comment by imSrbh** [comment]
@vinodbukya6 we you able to resolve 
`python3: /dvs/p4/build/sw/rel/gpgpu/MachineLearning/myelin_trt8/src/compiler/optimizer/cublas_impl.cpp:477: void add_heuristic_results_to_tactics(std::vector<cublasLtMatmulHeuristicResult_t>&, std::vectormyelin::ir::tactic_attribute_t&, myelin::ir::tactic_attribute_t&, bool): Assertion `false && "Invalid size written"' failed.`

**Comment by vinodbukya6** [comment]
Yeah, I am also facing the same issue. Not solved.

**Comment by vinodbukya6** [comment]
Hi @imSrbh, Any updates on the issue. Got any leads?

**Comment by vinodbukya6** [comment]
Hi, LPR engine file created using tlt-converter and followed mentioned steps.
Deepstream 5.1, cuda 11.1, TensorRT 7.2.
It's working fine for command:
python3 deepstream_lpr_app.py 1 2 0 file:///opt/nvidia/deepstream/deepstream-5.1/samples/streams/lpr-test1.mp4 out.mp4

Thank you so much.
